# theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins: jekyll-remote-theme
title: "Niquapod's Quest for Knowledge"
author: Niquapod
description: "This is a site to let me track my progress through the rooms of TryHackMe, and to keep notes on the tools used so I don't always have to refer back to a book."
