name: Generate Jekyll Archives
# description: Generate tags, months, and years archive files.
on:
  workflow_dispatch:
  push:
    paths:
      - "_posts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Jekyll Blog Archives
        uses: niquapod/jekyll-blog-archive-workflow@main
        with:
          archive_url: "https://niquapod.github.io/github-pages/archives/archivedata"
          archive_folder_path: "_archives"

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"s
          git config user.email "<>"          

      - name: commit
        run: |
          git add --all
          git commit -m "Created and updated archive files." || echo "No changes to commit."
          git push origin main || echo "No changes to push."          
